baseurl = "http://www.axolol.fr/"
title = "RedFish"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
  author = "RedFish"
  info = "Pentester | Cybersecurity Enthusiast"
  description = "RedFish's personal website and cybersecurity journey"
  keywords = "blog,cybersecurity,ctf,personal"
  avatarurl = "images/avatar3.jpg"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

customCSS = ["css/custom.css"]

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
# LinkedIn
  [[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    url = "https://fr.linkedin.com/in/arthur-pannier-7749ab1a0"

  # Root-Me (Icône Terminal)
  [[params.social]]
    name = "Root-Me"
    icon = "fas fa-terminal"
    url = "https://www.root-me.org/RedFish-331132"

  # Hack The Box (Icône Cube)
  [[params.social]]
    name = "Hack The Box"
    icon = "fas fa-cube"
    url = "https://app.hackthebox.com/users/247961"

  # YesWeHack (Icône Bug)
  [[params.social]]
    name = "YesWeHack"
    icon = "fas fa-bug"
    url = "https://yeswehack.com/hunters/RedFish"


# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

